server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddlAuto: update
      naming:
        implicitStrategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

  datasource:
    url: jdbc:postgresql://vinculus.postgres.database.azure.com:5432/postgres
    username: Vinculus
    password: Mechachieve@2025
    driverClassName: org.postgresql.Driver

  sql:
    init:
      mode: always
      platform: postgres

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB